kind: Service
apiVersion: v1
metadata:
  name: products-catalog-api
spec:
  type: NodePort
  selector:
    app: products-catalog-api
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: products-catalog-api-deployment
  labels:
    app: products-catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-catalog-api
  template:
    metadata:
      labels:
        app: products-catalog-api
    spec:
      containers:
      - name: products-catalog-api
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080